// <auto-generated />
using System;
using MasterDataAutomation.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterDataAutomation.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260830060915_AddCustomerCareModule")]
    partial class AddCustomerCareModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareAssignmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedByUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("FromDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("FromUserId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int?>("ToDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ToUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("TicketId");

                    b.HasIndex("ToDepartmentId");

                    b.HasIndex("ToUserId");

                    b.ToTable("CustomerCareAssignmentHistories", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("UploadedByUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UploadedAt");

                    b.ToTable("CustomerCareAttachments", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQualityCategory")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CustomerCareCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SALES",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complaints related to sales representatives, supervisors and sales handling.",
                            IsActive = true,
                            IsQualityCategory = false,
                            Name = "Sales & Representative",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "DELIVERY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complaints related to product supply, delivery and order fulfillment.",
                            IsActive = true,
                            IsQualityCategory = false,
                            Name = "Delivery & Supply",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "REPLACEMENT",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complaints related to refused or delayed product replacement.",
                            IsActive = true,
                            IsQualityCategory = false,
                            Name = "Product Replacement",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "FREEZER",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freezer requests, faults, maintenance and retrieval cases.",
                            IsActive = true,
                            IsQualityCategory = false,
                            Name = "Freezer & Maintenance",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "QUALITY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Product quality complaints and quality-related customer cases.",
                            IsActive = true,
                            IsQualityCategory = true,
                            Name = "Product Quality",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "COMMERCIAL",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New customer, contracting, pricing and commercial service requests.",
                            IsActive = true,
                            IsQualityCategory = false,
                            Name = "Commercial Requests",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "GENERAL_INQUIRY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "General inquiries, information requests and call transfers.",
                            IsActive = true,
                            IsQualityCategory = false,
                            Name = "General Inquiry",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Code = "OTHER",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cases that do not currently match another category.",
                            IsActive = true,
                            IsQualityCategory = false,
                            Name = "Other",
                            SortOrder = 99
                        });
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CustomerCareDepartments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CUSTOMER_CARE",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer care and complaint handling team.",
                            IsActive = true,
                            Name = "Customer Care",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "QUALITY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quality assurance and product complaint handling.",
                            IsActive = true,
                            Name = "Quality",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "SALES",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sales representatives and sales-related complaint handling.",
                            IsActive = true,
                            Name = "Sales",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "BRANCHES",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Branch-level operational complaint handling.",
                            IsActive = true,
                            Name = "Branches",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "DISTRIBUTION",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Distribution and delivery-related complaint handling.",
                            IsActive = true,
                            Name = "Distribution",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "MANAGEMENT",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Escalated cases requiring management intervention.",
                            IsActive = true,
                            Name = "Management",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareQualityDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompensationNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("CompensationQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompensationType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasHealthRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLegalRisk")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QualityDecision")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("QualityIssueDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("QualityIssueType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RiskNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("SampleCollected")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SampleCollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SampleRequired")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("CustomerCareQualityDetails", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareSlaPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EscalationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("FirstResponseMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseBusinessHours")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("TicketType", "CategoryId", "SubCategoryId", "Priority");

                    b.ToTable("CustomerCareSlaPolicies", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedByUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("TicketId");

                    b.ToTable("CustomerCareStatusHistories", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Code")
                        .IsUnique();

                    b.ToTable("CustomerCareSubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "SALES_REP_COMPLAINT",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complaint related to a sales representative.",
                            IsActive = true,
                            Name = "Sales Rep Complaint",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "SUPERVISOR_COMPLAINT",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complaint related to a sales supervisor.",
                            IsActive = true,
                            Name = "Supervisor Complaint",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Code = "SALES_REP_NO_RESPONSE",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer could not reach or receive a response from the sales representative.",
                            IsActive = true,
                            Name = "Sales Rep No Response",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Code = "NO_DELIVERY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Requested products were not delivered.",
                            IsActive = true,
                            Name = "No Delivery",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Code = "REFUSED_SUPPLY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Supply or product delivery was refused.",
                            IsActive = true,
                            Name = "Refused Supply",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Code = "INSUFFICIENT_QUANTITY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delivered quantity did not meet the customer's requested quantity.",
                            IsActive = true,
                            Name = "Insufficient Quantity",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Code = "DELIVERY_DELAY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delivery was delayed beyond the expected time.",
                            IsActive = true,
                            Name = "Delivery Delay",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Code = "REPLACEMENT_REFUSED",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Product replacement request was refused.",
                            IsActive = true,
                            Name = "Replacement Refused",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Code = "REPLACEMENT_DELAYED",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Product replacement was approved or requested but delayed.",
                            IsActive = true,
                            Name = "Replacement Delayed",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Code = "FREEZER_REQUEST",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer requested a company freezer.",
                            IsActive = true,
                            Name = "Freezer Request",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Code = "FREEZER_MAINTENANCE",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freezer requires maintenance.",
                            IsActive = true,
                            Name = "Freezer Maintenance",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Code = "COOLING_FAILURE",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freezer is not cooling or has stopped working.",
                            IsActive = true,
                            Name = "Cooling Failure",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Code = "FREEZER_RETRIEVAL",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer requested or requires freezer retrieval.",
                            IsActive = true,
                            Name = "Freezer Retrieval",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 5,
                            Code = "FOREIGN_OBJECT",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Foreign material was found inside the product.",
                            IsActive = true,
                            Name = "Foreign Object",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Code = "HAIR",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hair was found in the product.",
                            IsActive = true,
                            Name = "Hair in Product",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Code = "PLASTIC",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plastic material was found in the product.",
                            IsActive = true,
                            Name = "Plastic in Product",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Code = "METAL_OR_WIRE",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Metal or wire material was found in the product.",
                            IsActive = true,
                            Name = "Metal or Wire in Product",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Code = "TASTE_ISSUE",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer reported an abnormal or unacceptable taste.",
                            IsActive = true,
                            Name = "Taste Issue",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Code = "MELTED_PRODUCT",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Product was melted or affected by temperature handling.",
                            IsActive = true,
                            Name = "Melted Product",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Code = "ICE_CRYSTALS",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer reported abnormal ice crystals in the product.",
                            IsActive = true,
                            Name = "Ice Crystals",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Code = "PACKAGING_ISSUE",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complaint related to product packaging.",
                            IsActive = true,
                            Name = "Packaging Issue",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Code = "MISSING_PRODUCTION_DATE",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Production or expiry information is missing or unclear.",
                            IsActive = true,
                            Name = "Missing Production Date",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Code = "MISSING_COMPONENT",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Expected product component or ingredient is missing.",
                            IsActive = true,
                            Name = "Missing Product Component",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Code = "OTHER_QUALITY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Other product quality complaint.",
                            IsActive = true,
                            Name = "Other Quality Issue",
                            SortOrder = 99
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            Code = "NEW_CUSTOMER",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Request to register or contract a new customer.",
                            IsActive = true,
                            Name = "New Customer Request",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 6,
                            Code = "CONTRACT_REQUEST",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer requested contracting or commercial onboarding.",
                            IsActive = true,
                            Name = "Contract Request",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 6,
                            Code = "PRICING_INQUIRY",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer requested product or commercial pricing information.",
                            IsActive = true,
                            Name = "Pricing Inquiry",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 7,
                            Code = "GENERAL_INFORMATION",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "General customer inquiry.",
                            IsActive = true,
                            Name = "General Information",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 7,
                            Code = "CALL_TRANSFER",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer communication requires transfer to another party.",
                            IsActive = true,
                            Name = "Call Transfer",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 8,
                            Code = "OTHER",
                            CreatedAt = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Case does not match an existing subcategory.",
                            IsActive = true,
                            Name = "Other",
                            SortOrder = 99
                        });
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EscalationDueAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstRespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstResponseDueAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstResponseBreached")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResolutionBreached")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextFollowUpAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolutionDueAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolutionSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SalesRepId")
                        .HasColumnType("int");

                    b.Property<int?>("SlaPolicyId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDepartmentId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerPhone");

                    b.HasIndex("NextFollowUpAt");

                    b.HasIndex("Priority");

                    b.HasIndex("ResolutionDueAt");

                    b.HasIndex("SlaPolicyId");

                    b.HasIndex("Status");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("CustomerCareTickets", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicketAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("FollowUpAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInternalNote")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FollowUpAt");

                    b.HasIndex("TicketId");

                    b.ToTable("CustomerCareTicketActions", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.AppUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.Customers.CustomerModificationRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CurrentCustomerType")
                        .HasColumnType("int");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ModificationType")
                        .HasColumnType("int");

                    b.Property<string>("NewMarketName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode");

                    b.HasIndex("Status");

                    b.ToTable("CustomerModificationRequests", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.DraftCustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SalesDistrict")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Draft");

                    b.HasKey("Id");

                    b.ToTable("DraftCustomers", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.GenerationHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomersCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("FirstBpCode")
                        .HasColumnType("int");

                    b.Property<int>("LastBpCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("GenerationHistories", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.Products.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("MarketValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MarketValidTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OutletSellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RetailSellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RetailValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RetailValidTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.Products.ProductRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountsManagerReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BonusQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAsProductAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ExecutiveManagerReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasBonus")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("OutletSellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PiecePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PiecesCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("RetailSellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode");

                    b.ToTable("ProductRequests", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SalesAnalytics.SalesAnalyticsCustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerAccountGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerClassificationCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerClassificationName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("IncotermsCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IncotermsName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SalesDistrictCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesDistrictName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SearchTerm")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SearchTerm2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SourceCreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("SourceCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UploadBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("SalesDistrictCode");

                    b.HasIndex("UploadBatchId");

                    b.ToTable("SalesAnalyticsCustomers", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SalesAnalytics.SalesAnalyticsDailySalesReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CityName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SalesAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAfterTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBeforeTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UploadBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityCode");

                    b.HasIndex("CustomerCode");

                    b.HasIndex("LineCode");

                    b.HasIndex("ProductCode");

                    b.HasIndex("ReportDate");

                    b.ToTable("SalesAnalyticsDailySalesReports", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SalesAnalytics.SalesAnalyticsDailyVisitReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NegativeReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalesRepCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesRepName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("SuccessfulVisitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupervisorName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UploadBatchId")
                        .HasColumnType("int");

                    b.Property<string>("VisitCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisitDurationText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VisitEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode");

                    b.HasIndex("ReportDate");

                    b.HasIndex("SalesRepCode");

                    b.HasIndex("UploadBatchId");

                    b.HasIndex("VisitStatus");

                    b.ToTable("SalesAnalyticsDailyVisitReports", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SalesAnalytics.SalesAnalyticsMtdSalesReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CityName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalesAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAfterTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBeforeTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UploadBatchId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityCode");

                    b.HasIndex("CustomerCode");

                    b.HasIndex("ProductCode");

                    b.HasIndex("Year", "Month", "ToDate");

                    b.ToTable("SalesAnalyticsMtdSalesReports", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SalesAnalytics.SalesAnalyticsMtdVisitReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("NegativeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SalesRepCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesRepName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("SuccessfulVisitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupervisorName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadBatchId")
                        .HasColumnType("int");

                    b.Property<string>("VisitCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitDurationText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VisitEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitStatus")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode");

                    b.HasIndex("SalesRepCode");

                    b.HasIndex("VisitCode");

                    b.HasIndex("VisitDate");

                    b.HasIndex("Year", "Month", "ToDate");

                    b.ToTable("SalesAnalyticsMtdVisitReports", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SalesAnalytics.SalesAnalyticsSalesRepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("InternalCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegionName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SalesRepCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesRepName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SearchTerm2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SourceCreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("SourceCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UploadBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode");

                    b.HasIndex("InternalCode");

                    b.HasIndex("SalesRepCode")
                        .IsUnique();

                    b.HasIndex("UploadBatchId");

                    b.ToTable("SalesAnalyticsSalesReps", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SalesAnalytics.SalesAnalyticsUploadBatchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FailedRows")
                        .HasColumnType("int");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<int>("ImportedRows")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FileType");

                    b.HasIndex("ReportDate");

                    b.HasIndex("UploadDate");

                    b.ToTable("SalesAnalyticsUploadBatches", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SalesAnalytics.SalesDistrictMonthlyTargetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlySalesTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlannedVisits")
                        .HasColumnType("int");

                    b.Property<string>("SalesDistrictCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesDistrictName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode");

                    b.HasIndex("SalesDistrictCode");

                    b.HasIndex("Year", "Month", "SalesDistrictCode")
                        .IsUnique();

                    b.ToTable("SalesDistrictMonthlyTargets", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SalesAnalytics.SalesRepRouteAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SalesDistrictCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesDistrictName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SalesRepCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesRepName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("UploadBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode");

                    b.HasIndex("IsActive");

                    b.HasIndex("SalesDistrictCode");

                    b.HasIndex("SalesRepCode");

                    b.HasIndex("UploadBatchId");

                    b.ToTable("SalesRepRouteAssignments", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.System.ActivityLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Infrastructure.Data.Entities.SystemSettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareAssignmentHistory", b =>
                {
                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicket", "Ticket")
                        .WithMany("AssignmentHistory")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareAttachment", b =>
                {
                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareQualityDetail", b =>
                {
                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicket", "Ticket")
                        .WithOne("QualityDetail")
                        .HasForeignKey("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareQualityDetail", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareSlaPolicy", b =>
                {
                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareSubCategory", null)
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareStatusHistory", b =>
                {
                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicket", "Ticket")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareSubCategory", b =>
                {
                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareCategory", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicket", b =>
                {
                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareDepartment", "AssignedDepartment")
                        .WithMany()
                        .HasForeignKey("AssignedDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareSlaPolicy", "SlaPolicy")
                        .WithMany()
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareSubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedDepartment");

                    b.Navigation("Category");

                    b.Navigation("SlaPolicy");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicketAction", b =>
                {
                    b.HasOne("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicket", "Ticket")
                        .WithMany("Actions")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("MasterDataAutomation.Domain.Modules.CustomerCare.Entities.CustomerCareTicket", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("AssignmentHistory");

                    b.Navigation("Attachments");

                    b.Navigation("QualityDetail");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
